version: "3.7"
services:
  server:
    build: .
    container_name: mywatchlist_server
    network_mode: "host"
    restart: always
    volumes:
      - ~/caddy_data:/data
      - ~/caddy_config:/config

  backend:
    build: ./mywatchlist
    env_file: ./config_spring.env
    container_name: mywatchlist_backend
    network_mode: "host"
    restart: always
  
  db:
    image: postgres:14
    container_name: mywatchlist_db
    restart: always
    env_file: ./config.env
    network_mode: "host"
    volumes:
      - ~/postgres_data:/var/lib/postgresql/data
